name: octoprint-inofficial # 
version: '1.3.2' # from official 1.3.2 branch
summary: inofficial snap of the octoprint 3D printer webinterface
description: |
  OctoPrint provides a intuitive web interface for controlling consumer 3D printers.
  It is Free Software and released under the GNU Affero General Public License V3.
  Its website can be found at octoprint.org.
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # assuming we have everything in place...

apps:
  octoprint:
    command: octoprint
    plugs: [network, network-bind, raw-usb]

parts:
  octoprint:
    source: https://github.com/foosel/OctoPrint.git
    source-tag: master
    plugin: python
    python-version: python2
